### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [TheTensorDude/vision_transformer_tf#1]
First, thank you for sharing this project with us!

Could you please add an explicit `LICENSE` file to the repo so that it's clear
under what terms the content is provided, and under what terms user
contributions are licensed?

Per [GitHub docs on licensing][github-docs-licensing]:

> [...] without a license, the default copyright laws apply, meaning that you
> retain all rights to your source code and no one may reproduce, distribute,
> or create derivative works from your work. If you're creating an open source
> project, we strongly encourage you to include an open source license.

Thanks!

[github-docs-licensing]: https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license

**Comment by hrithickcodes** [comment]
Done!

**Comment by mbrukman** [comment]
Thank you for taking a look and fixing this! Much appreciated.

Would you mind fixing this for your other widely-applicable and useful repos, e.g., https://github.com/TheTensorDude/transformer-tf or would you like me to file a similar issue there as well to track this?
